---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repositories
    apt:
      update_cache: yes
    changed_when: False
  
  # Load distro-specific variables
  - name: Include vars of ubuntu.yml into the 'stuff'
    include_vars:
      file: vars/Ubuntu.yml
      name: stuff
  
  tasks:
   - include: tasks/user.yml
   - include: tasks/cron.yml
   - include: tasks/packages.yml
   
    

...