---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repositories
    apt:
      update_cache: yes
    changed_when: False
  
  # Load distro-specific variables
  - include_vars:
    file: vars/Ubuntu.yml
    tags: always
  
  tasks:
   - include: tasks/user.yml
   - include: tasks/cron.yml
   - include: tasks/packages.yml
   
    

...