- name: "Install apt-transport-https"
  ansible.builtin.apt: 
    name: apt-transport-https
    state: latest
    update_cache: true
  
- name: "Add apt signing key"
  ansible.builtin.apt_key: 
    state: present
    url: "https://packages.microsoft.com/keys/microsoft.asc"
  
- name: "Add repository into sources list"
  ansible.builtin.apt_repository: 
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
  
- name: "Install visual studio code"
  ansible.builtin.apt: 
    name: code
    state: latest
    update_cache: true