- name: "Install apt-transport-https"
  ansible.builtin.apt: 
    name: apt-transport-https
    state: latest
    update_cache: true
  
- name: "Add apt signing key"
  ansible.builtin.apt_key: 
    state: present
    url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
  
- name: "Add repository into sources list"
  ansible.builtin.apt_repository: 
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave-browser-release
  
- name: "Install brave-browser-release"
  ansible.builtin.apt: 
    name: brave-browser
    state: latest
    update_cache: true